spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm?userSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: book-interface
  thymeleaf:
    cache: false #关闭缓存
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

mybatis:
  type-aliases-package: com.aaa.momdel
  mapper-locations: classpath:mapper/*Mapper.xml

eureka:
  client:
    service-url:
      defaultZone: http://eureka6081:6081/eureka/